
#=================================================================================
# 容器相关设置

#=================================================================================
# spring 组件相关设置
spring:
  application:
    name: tkey-sso-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  #    active: 'gatling'
  jackson:
    default-property-inclusion: non_null
    date-format: 'yyyy-MM-dd HH:mm:ss'
  thymeleaf:
    encoding: utf-8
    prefix: 'classpath:/templates/'
    suffix: '.html'
    cache: false
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tkey_sso?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 100
      minimum-idle: 100
      max-lifetime: 1800000
      connection-test-query: 'SELECT 1'
      pool-name: myHikariPoolName
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        # 默认用的是hibernate源码中用的是TreeMap存储实体类字段, 这样创建的表的顺序是乱序的
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  #缓存配置
  cache:
    ehcache:
      config: classpath:config/ehcache.xml
# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  server:
    servlet:
      context-path: /tkey-actuator


#=================================================================================
# 其他辅助框架相关配置

#=================================================================================
# 自定义参数相关配置


#=================================================================================
