
#=================================================================================
# 容器相关设置
debug: false
server:
  port: 9091
  servlet:
    context-path: /sso
  tomcat:
    max-connections: 10000
    max-threads: 200
    min-spare-threads: 200
  connection-timeout: 5000ms
logging:
  config: classpath:logback/logback-dev.xml

#=================================================================================
# spring 组件相关设置
spring:
  application:
    name: tkey-sso-server
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:dev}
#   active: 'gatling'
  jackson:
    default-property-inclusion: non_null
    date-format: 'yyyy-MM-dd HH:mm:ss'
  #------------------------------------------------- 模板
  thymeleaf:
    encoding: utf-8
    prefix: 'classpath:/templates/'
    suffix: '.html'
    cache: false
  devtools:
    restart:
      enabled: false
  #------------------------------------------------- 缓存
  redis:
    database: ${SPRING_REDIS_DATABASE:0}
    port: ${SPRING_REDIS_PORT:6379}
    host: ${SPRING_REDIS_HOST:redis.honezhi.com}
    #password: ${SPRING_REDIS_PASSWORD:123456}
    timeout: 10000ms
    lettuce:
      pool:
        max-active: -1
        max-idle: -1
        min-idle: 200
        max-wait: 2000ms
  #Java缓存
  cache:
    ehcache:
      config: classpath:config/ehcache.xml
  #------------------------------------------------- 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/honezhi_sso?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: lisago
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 100
      minimum-idle: 100
      max-lifetime: 1800000
      connection-test-query: 'SELECT 1'
      pool-name: myHikariPoolName
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        # 默认用的是hibernate源码中用的是TreeMap存储实体类字段, 这样创建的表的顺序是乱序的
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
#------------------------------------------------- springboot健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  server:
    servlet:
      context-path: /sso-actuator


#=================================================================================
# 其他辅助框架相关配置

#=================================================================================
# 自定义参数相关配置
tkey:
  sso:
    oauth:
      error-uri-msg: "See the full API docs at https://github.com/cdk8s"
      # 用于 token 前缀，表名是哪个节点服务生成的 token
      node-number: ${TKEY_NODE_NUMBER:10}
      tgc-cookie-secure: false
      remember-me-max-time-to-live-in-seconds: 604800
      code-max-time-to-live-in-seconds: 120
      access-token-max-time-to-live-in-seconds: 43200
      refresh-token-max-time-to-live-in-seconds: 86400
      tgc-and-user-info-max-time-to-live-in-seconds: 86400


#=================================================================================
